WhiteLaggon.Web/Controllers/ContaController.cs
using CardosoResort.Application.Common.Interfaces;
using CardosoResort.Application.Common.Utility;
using CardosoResort.Domain.Entities;
using CardosoResort.Web.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CardosoResort.Web.Controllers
{
    public class ContaController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;//IUnitOfWork é uma interface que contém métodos para manipular o banco de dados
        private readonly UserManager<ApplicationUser> _userManager; //UserManager é uma classe do Identity que contém métodos para manipular usuários
        private readonly SignInManager<ApplicationUser> _signInManager; //SignInManager é uma classe do Identity que contém métodos para autenticar usuários. Responsável por gerenciar o login do usuário

        private readonly RoleManager<IdentityRole> _roleManager; //RoleManager é uma classe do Identity que contém métodos para manipular roles

        public ContaController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, RoleManager<IdentityRole> roleManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }

        [HttpGet]
        public IActionResult Login(string redireccionarURL = null) //O parâmetro returnUrl é utilizado para redirecionar o usuário para a página que ele estava antes de ser redirecionado para a página de login
        {
            if (Request.Query.ContainsKey("ReturnUrl"))
            {
                redireccionarURL = Request.Query["ReturnUrl"].ToString();
            }

            LoginVM loginVM = new LoginVM
            {
                RedireccionarURL = redireccionarURL //Atribui a URL para onde o usuário vai ser redirecionado após o login
            };
            return View(loginVM); //Retorna a view de login
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginVM loginVM)
        {
            if (ModelState.IsValid)
            {
                //O método PasswordSignInAsync é chamado no objeto _signInManager para autenticar o usuário com o email e a senha fornecidos no loginVM. Ele retorna uma tarefa (Task) que representa a operação assíncrona de autenticar o usuário.
                var result = await _signInManager //
                    .PasswordSignInAsync(loginVM.Email, loginVM.Password, loginVM.LembrarMe, lockoutOnFailure: false);

                if (result.Succeeded)
                {   //pY9h@Hj$ZS
                    string nome = _signInManager.Context.User.Identity.Name;

                    TempData["SucessoLogin"] = $"Bem-vindo {nome}";
                    if (string.IsNullOrEmpty(loginVM.RedireccionarURL))
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        return LocalRedirect(loginVM.RedireccionarURL);
                    }
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Login inválido");
                TempData["ErroLogin"] = "Login inválido";
            }
            return View(loginVM); //Retorna a view de login
        }

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync(); //O método SignOutAsync é chamado no objeto _signInManager para desautenticar o usuário. Ele retorna uma tarefa (Task) que representa a operação assíncrona de desautenticar o usuário.
            TempData["SucessoLogout"] = "Logout efetuado com sucesso";
            return RedirectToAction("Index", "Home"); //Redireciona o usuário para a página inicial do site
        }

        public IActionResult AcessoNegado()
        {
            return View(); //Retorna a view de acesso negado
        }

        public IActionResult Registar()
        {
            /*explicação passo a passo do que está acontecendo:
1.	_roleManager.RoleExistsAsync("Administrador"): O método RoleExistsAsync é chamado no objeto _roleManager para verificar se o papel chamado "Administrador" existe no banco de dados. Esse método retorna uma tarefa (Task) que representa a operação assíncrona de verificar a existência do papel.
2.	.GetAwaiter(): O método GetAwaiter() é chamado na tarefa retornada pelo método RoleExistsAsync. Ele retorna um objeto awaiter que permite aguardar a conclusão da tarefa assíncrona.
3.	.GetResult(): O método GetResult() é chamado no awaiter para obter o resultado da tarefa assíncrona. Nesse caso, ele bloqueia a execução do código até que a tarefa seja concluída e retorna o resultado.
4.	!: O operador de negação é usado para inverter o resultado retornado pelo método RoleExistsAsync. Se o papel "Administrador" não existir, o resultado será false, e a condição do if será verdadeira*/

            //Verifica se a role Admin e User existem no banco de dados e cria se não existirem na tabela AspNetRoles
            if (!_roleManager.RoleExistsAsync(SD.Role_Administrador).GetAwaiter().GetResult())
            {//Cria um role Admin no banco de dados se ele não existir
                _roleManager.CreateAsync(new IdentityRole(SD.Role_Administrador)).Wait();
                _roleManager.CreateAsync(new IdentityRole(SD.Role_Utilizador)).Wait();
            }

            RegistoVM registoVM = new RegistoVM
            {
                //Obtém a lista de roles disponíveis no sistema e atribui à propriedade RolesLista
                RolesLista = _roleManager.Roles.Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Name
                })
            };
            return View(registoVM);
        }

        [HttpPost]
        public async Task<IActionResult> Registar(RegistoVM registoVM)
        {
            if (ModelState.IsValid) //Se o modelo for válido
            {
                //Criamos um objeto ApplicationUser com os dados do registoVM para ser inserido na tabela AspNetUsers
                ApplicationUser user = new ApplicationUser
                {
                    //Campos vem da tabela AspNetUsers
                    UserName = registoVM.Email,
                    Email = registoVM.Email,
                    Nome = registoVM.Nome,
                    PhoneNumber = registoVM.Telemovel,
                    Data_Criacao = DateTime.Now,
                    NormalizedUserName = registoVM.Email.ToUpper(),
                    NormalizedEmail = registoVM.Email.ToUpper()
                };

                //Cria um utilizador na tabela AspNetUsers com o helper
                var result = await _userManager.CreateAsync(user, registoVM.Password); //O método CreateAsync cria um novo usuário na tabela AspNetUsers com os dados fornecidos no objeto ApplicationUser e a senha fornecida no parâmetro password. Ele retorna uma tarefa (Task) que representa a operação assíncrona de criar o usuário.

                if (result.Succeeded)//Se o usuário for criado com sucesso
                {
                    if (!string.IsNullOrEmpty(registoVM.Role))
                    {
                        //Adiciona o utilizador à role selecionada
                        await _userManager.AddToRoleAsync(user, registoVM.Role);//O método AddToRoleAsync adiciona o usuário criado à role selecionada no parâmetro role. Ele retorna uma tarefa (Task) que representa a operação assíncrona de adicionar o usuário à role.
                    }
                    else
                    {
                        //Adiciona o utilizador à role Utilizador caso não tenha sido selecionada nenhuma role
                        await _userManager.AddToRoleAsync(user, SD.Role_Utilizador);
                    }

                    await _signInManager.SignInAsync(user, isPersistent: false);//O método SignInAsync autentica o usuário criado no sistema. Ele retorna uma tarefa (Task) que representa a operação assíncrona de autenticar o usuário. O parâmetro isPersistent indica se o cookie de autenticação deve ser persistente ou não.

                    if (string.IsNullOrEmpty(registoVM.RedireccionarURL)) //Se a propriedade RedireccionarURL for nula ou vazia
                    {
                        return RedirectToAction("Index", "Home"); //Redireciona o usuário para a página inicial do site
                    }
                    else
                    {
                        return LocalRedirect(registoVM.RedireccionarURL); //Redireciona o usuário para a URL fornecida no parâmetro RedireccionarURL pelo LocalRedirect (redireciona para uma URL local). Prevente ataques de redirecionamento aberto
                    }
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description); //Adiciona um erro ao ModelState para cada erro retornado pelo método CreateAsync
                }
            }

            //Se o modelo não for válido ou ocorrer algum erro, o objeto registoVM é retornado para a view

            //Objeto registoVM vai ser atualizado com a lista de roles disponíveis no sistema e o antigo registoVM vai ser mandado para garbage collection
            registoVM.RolesLista = _roleManager.Roles.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Name
            });

            return View(registoVM);
        }
    }
}

WhiteLaggon.Web/Controllers/ExtrasController.cs
using CardosoResort.Application.Common.Interfaces;
using CardosoResort.Application.Common.Utility;
using CardosoResort.Domain.Entities;
using CardosoResort.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CardosoResort.Web.Controllers
{
    [Authorize(Roles = SD.Role_Administrador)] //Atributo que indica que apenas utilizadores com a role de administrador podem aceder a este controlador. Também pode ser aplicado a um método específico
    public class ExtrasController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ExtrasController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index(int? dropDownVilla)
        {
            var extras = _unitOfWork.Extras.GetAll(includeProperties: "Villa").Where(e => dropDownVilla == null || e.VillaId == dropDownVilla).ToList();

            List<Villa> villas = _unitOfWork.Villas.GetAll().ToList(); // Fetch the villas from your database
            villas.Insert(0, new Villa { Id = 0, Nome = "Todas as villas" }); // Insert the new item at the beginning
            ViewBag.LISTAVILLAS = new SelectList(villas, "Id", "Nome"); // C

            ViewBag.LISTAVILLAS = new SelectList(_unitOfWork.Villas.GetAll(), "Id", "Nome"); //Aqui estamos criando um SelectList com o nome e o id das villas

            return View(extras);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ExtraVM extraVM = new ExtraVM
            {
                Extra = new Extra(),
                VillaLista = new SelectList(_unitOfWork.Villas.GetAll(), "Id", "Nome")
            };
            return View(extraVM);
        }

        [HttpPost]
        public IActionResult Create(ExtraVM objeto)
        {
            bool extraExiste = _unitOfWork.Extras.GetAll().Any(e => e.Nome == objeto.Extra.Nome && e.VillaId == objeto.Extra.VillaId);
            if (extraExiste)
            {
                TempData["error"] = $"Extra {objeto.Extra.Nome} já existe na mesma Villa";
                ModelState.AddModelError("Nome", "Extra já existe");
                objeto.VillaLista = new SelectList(_unitOfWork.Villas.GetAll(), "Id", "Nome");
                return View(objeto);
            }

            if (ModelState.IsValid)
            {
                _unitOfWork.Extras.Add(objeto.Extra);
                _unitOfWork.Save();
                TempData["success"] = $"Extra {objeto.Extra.Nome} adicionado com sucesso";
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public IActionResult Atualizar(int extraId)
        {
            ExtraVM? extraVM = new ExtraVM
            {
                Extra = _unitOfWork.Extras.Get(e => e.Id == extraId),
                VillaLista = new SelectList(_unitOfWork.Villas.GetAll(), "Id", "Nome")
            };

            if (extraVM.Extra == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(extraVM);
        }

        [HttpPost]
        public IActionResult Atualizar(ExtraVM objeto)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Extras.Update(objeto.Extra);
                _unitOfWork.Save();
                TempData["success"] = $"Extra {objeto.Extra.Nome} atualizado com sucesso";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "Erro ao atualizar o extra";
            objeto.VillaLista = new SelectList(_unitOfWork.Villas.GetAll(), "Id", "Nome");
            return View();
        }

        [HttpGet]
        public IActionResult Apagar(int extraId)
        {
            ExtraVM? extraVM = new ExtraVM
            {
                Extra = _unitOfWork.Extras.Get(e => e.Id == extraId),
                VillaLista = new SelectList(_unitOfWork.Villas.GetAll(), "Id", "Nome")
            };

            if (extraVM.Extra == null)
            {
                TempData["error"] = "Extra não encontrado";
                return RedirectToAction("Error", "Home");
            }
            return View(extraVM);
        }

        [HttpPost]
        public IActionResult Apagar(ExtraVM objeto)
        {
            Extra? objetoBd = _unitOfWork.Extras.Get(v => v.Id == objeto.Extra.Id);

            //Verificar se a fracao foi encontrada
            if (objetoBd is not null)
            {
                _unitOfWork.Extras.Remove(objetoBd);
                _unitOfWork.VillasFracao.Save(); //Salvamos as alterações no banco de dados
                TempData["success"] = $"Extra {objeto.Extra.Nome} foi apagado com sucesso"; //U
                return RedirectToAction(nameof(Index)); //Se o modelo for válido, redirecionamos para a página de índice com o nameof(Index) para evitar erros de digitação
            }

            TempData["error"] = "Erro ao apagar extra"; //Usamos TempData para enviar uma mensagem de erro para a próxima solicitação
            objeto.VillaLista = new SelectList(_unitOfWork.Villas.GetAll(), "Id", "Nome"); //Recarregar a lista de villas para o dropdownList após a validação, caso contrário, a lista será perdida
            return View(objeto); //Se o modelo não for válido mandar de volta para a página de criação
        }
    }
}

WhiteLaggon.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CardosoResort.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CardosoResort.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/CardosoResort.png" style="width:150px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Gestor do Resort
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Villa" asp-action="Index">Lista Resort</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="VillaFracao" asp-action="Index">Lista Fracao</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Extras" asp-action="Index">Lista Extras</a></li>

                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                    <partial name="_Login" />
                </div>
            </div>
            
        </nav>
    </header>
    <div class=""> @*Removido container*@
        <main role="main"> @*Removid padding*@
            <partial name="_Notification">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - <img src="~/Images/CardosoResort.png" style="width:150px" /> - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WhiteLaggon.Web/Views/Shared/_Login.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<ul class="navbar-nav">
    @if(SignInManager.IsSignedIn(User))
    {
        var user = await UserManager.GetUserAsync(User);
        var roles = await UserManager.GetRolesAsync(user);
        <li class="nav-item">
            <a class="nav-link" asp-controller="Home" asp-action="Index">Olá, @roles[0].ToString() @UserManager.GetUserName(User)</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Conta" asp-action="Logout">Logout</a>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link" asp-controller="Conta" asp-action="Login">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Conta" asp-action="Registar">Registo</a>
        </li>
    }
    

WhiteLaggon.Web/Views/Shared/_Notification.cshtml
@*ISTO E UMA PARTIAL VIEW

1. A partial view é um arquivo Razor (.cshtml) que contém um trecho de código HTML e C# que pode ser reutilizado em várias páginas da aplicação.
2. Neste caso, a partial view _Notification.cshtml é usada para exibir mensagens de erro ou sucesso na interface do usuário.
3. O código verifica se existem mensagens de erro ou sucesso armazenadas na variável TempData e exibe essas mensagens na página.
4. Nao esquecer de adicionar o toastr no layout principal, para que a partial view funcione corretamente.
5. Nao esquecer de adicionar css e js do toastr no layout principal, para que a partial view funcione corretamente.
*@


@*O código selecionado é uma parte de um arquivo de layout em uma aplicação web usando a linguagem Razor.
            Essa parte do código verifica se existem mensagens de erro ou sucesso armazenadas na variável TempData e exibe essas mensagens na página.
            A estrutura condicional @if(TempData["error"]!=null) verifica se a variável TempData contém uma mensagem de erro.
            Se for verdadeiro, um elemento <div> com a classe "alert alert-danger" é exibido na página, mostrando o conteúdo da mensagem de erro armazenada em TempData.
            Da mesma forma, a estrutura condicional @if(TempData["success"]!=null) verifica se a variável
            TempData contém uma mensagem de sucesso. Se for verdadeiro, um elemento <div> com a classe "alert alert-success" é exibido na página, mostrando o conteúdo da mensagem de sucesso armazenada em TempData.
            Essas estruturas condicionais permitem exibir mensagens de erro ou sucesso para o usuário, dependendo do que está armazenado em TempData. Isso pode ser útil para fornecer feedback ao usuário após a execução de determinadas ações na aplicação. *@
@if (TempData["error"] != null) //Se existir uma mensagem de erro que foi passada pelo controller
{
    //Jquery necessario para o toastr
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

                //Adiciona o script do toastr
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.warning('@TempData["error"]')
    </script>
}
@if (TempData["ErroLogin"] != null) //Se existir uma mensagem de erro que foi passada pelo controller
{
    //Jquery necessario para o toastr
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

                //Adiciona o script do toastr
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.error('@TempData["ErroLogin"]')
    </script>
}

@if (TempData["SucessoLogin"] != null) //Se existir uma mensagem de sucesso que foi passada pelo controller
{
    //Jquery necessario para o toastr
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

                //Adiciona o script do toastr
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["SucessoLogin"]')
    </script>
}

@if (TempData["SucessoLogout"] != null) //Se existir uma mensagem de sucesso que foi passada pelo controller
{
    //Jquery necessario para o toastr
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

                //Adiciona o script do toastr
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["SucessoLogout"]')
    </script>
}

@if (TempData["success"] != null) //Se existir uma mensagem de sucesso que foi passada pelo controller
{
    //Atençao, tem que ser mesmoassim, se nao nao funciona

    //Jquery necessario para o toastr
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    //Adiciona o script do toastr
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

@if(TempData["info"] != null) //Se existir uma mensagem de informacao que foi passada pelo controller
{
    //Jquery necessario para o toastr
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    //Adiciona o script do toastr
    <script type="text/javascript">
        toastr.info('@TempData["info"]')
    </script>
}

WhiteLaggon.Web/Views/Shared/_VillaDetalhes.cshtml
@model Villa

<div class="row">
    <div class="col-12 col-md-5">
        <img src="@Model.ImagemUrl" style="border-radius:10px;" width="100%" />
    </div>
    <div class="col-12 col-md-7">
        <div class="row p-2">
            <div class="col-12">
                <p class="card-title text-warning" style="font-size:xx-large">@Model.Nome</p>
                <p class="card-text" style="font-size:large">
                    @Html.Raw(Model.Descricao)
                </p>
                <p class="h5 text-black">
                    Extras:
                    @if (Model.VillaExtra.Count() > 0 && Model.VillaExtra != null)
                    {
                        @foreach (var extra in Model.VillaExtra)
                        {
                            <span class="badge bg-success">@extra.Nome</span>
                        }
                    }
                </p>

            </div>
        </div>
        <div class="row col-12">
            <span class="text-end p-0 pt-3 m-0">
                <span class="float-right">Máxima Ocupação: @Model.Ocupacao adultos</span><br />
                <span class="float-right pt-1">Área da Villa : @Model.Metros_Quadrados m<sup>2</sup></span><br />
                <p class="text-warning font-weight-bold pt-1">
                    <span style=" #ff6a00">
                        €@Model.Preco/noite
                    </span>
                </p>
            </span>
        </div>
    </div>
</div>