WhiteLaggon.Web/Controllers/VillaNumeroController.cs
using CardosoResort.Domain.Entities;
using CardosoResort.Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;

namespace CardosoResort.Web.Controllers
{
    public class VillaNumeroController : Controller
    {
        //Com .net Core o contexto do banco de dados é injetado no controlador por meio do construtor
        //Portanto apenas buscamos o DB que já foi configurado no Program.cs e buscamos a implementação do DbContext
        //O que vai configurar a connectionString, abrir connexao e dar a connexao
        private readonly ApplicationDbContext _db;

        public VillaNumeroController(ApplicationDbContext db)
        {
            //Aqui, Dependency Injection é usada para injetar o contexto do banco de dados no controlador
            _db = db;
        }

        public IActionResult Index()
        {
            var villasNumeros = _db.VillaNumeros.ToList();
            return View(villasNumeros);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(VillaNumero villaNumero)
        {
            ModelState.Remove("Villa"); //Removemos a validação do campo VillaId.
            if (ModelState.IsValid)
            {
                _db.VillaNumeros.Add(villaNumero);
                _db.SaveChanges();
                TempData["success"] = "Numero para a vila foi criada com sucesso"; //Usamos TempData para enviar uma mensagem de sucesso para a próxima solicitação
                return RedirectToAction("Index"); //Se o modelo for válido, redirecionamos para a página de índice
            }
            TempData["error"] = "Erro ao criar a villa"; //Usamos TempData para enviar uma mensagem de erro para a próxima solicitação
            return View(); //Se o modelo não for válido mandar de volta para a página de criação
        }

        public IActionResult Atualizar(int villaId)
        {
            Villa? villa = _db.Villas.FirstOrDefault(v => v.Id == villaId); //Buscamos a villa pelo id
            if (villa == null) //Se a villa não for encontrada, retornamos um erro 404
            {
                return RedirectToAction("Error", "Home");
            }

            return View(villa);
        }

        [HttpPost]
        public IActionResult Atualizar(Villa villa)
        {
            if (villa.Nome == villa.Descricao)
            {
                ModelState.AddModelError("Descricao", "O nome e a descrição não podem ser iguais");
            }
            if (ModelState.IsValid)
            {
                _db.Villas.Update(villa);
                _db.SaveChanges();
                TempData["success"] = "Villa foi atualizada com sucesso"; //Usamos TempData para enviar uma mensagem de sucesso para a próxima solicitação
                return RedirectToAction("Index"); //Se o modelo for válido, redirecionamos para a página de índice
            }
            TempData["error"] = "Erro ao atualizar a villa"; //Usamos TempData para enviar uma mensagem de erro para a próxima solicitação
            return View(); //Se o modelo não for válido mandar de volta para a página de criação
        }

        public IActionResult Apagar(int villaId)
        {
            Villa? villa = _db.Villas.FirstOrDefault(v => v.Id == villaId); //Buscamos a villa pelo id
            if (villa is null) //Usar o operador de nulidade para verificar se a villa é nula, evita overflow
            {
                return RedirectToAction("Error", "Home");
            }
            else
            {
                return View(villa);
            }
        }

        [HttpPost]
        public IActionResult Apagar(Villa villa)
        {
            //
            Villa? villaDb = _db.Villas.FirstOrDefault(v => v.Id == villa.Id); //Buscamos a villa pelo id
            if (villaDb is not null)
            {
                _db.Villas.Remove(villaDb);
                _db.SaveChanges();
                TempData["success"] = "Villa foi removida com sucesso"; //Usamos TempData para enviar uma mensagem de sucesso para a próxima solicitação
                //palavra success tem que ser igual a que está no arquivo _Layout.cshtml
                return RedirectToAction("Index");
            }
            TempData["error"] = "Villa não encontrada"; //Usamos TempData para enviar uma mensagem de erro para a próxima solicitação
            return View();
        }
    }
}

WhiteLaggon.Web/Views/VillaNumero/Create.cshtml
@model VillaNumero

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Criar novo Villa numero</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <div class="p-3">
                @*<div asp-validation-summary="All"></div> @*linha para colocar todos as validacoes*@
                <div class="form-floating py-1 col-12">
                    <input asp-for="VillaId" class="form-control border shadow" />
                    <label asp-for="VillaId" class="ms-2"></label>
                    <span asp-validation-for="VillaId" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Villa_Numero" class="form-control border shadow" />
                    <label asp-for="Villa_Numero" class="ms-2"></label>
                    <span asp-validation-for="Villa_Numero" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Detalhes_Especiais" class="form-control border shadow" />
                    <label asp-for="Detalhes_Especiais" class="ms-2"></label>
                    <span asp-validation-for="Detalhes_Especiais" class="text-danger"></span>
                </div>
            </div>

            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-success w-100">
                        <i class="bi bi-check-circle"></i> Criar
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="VillaNumero" asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"></i> Cancelar
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>


@*Valida;oes no lado do cliente. Assim, nao ]e preciso fazer post*@
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteLaggon.Web/Views/VillaNumero/Index.cshtml
@model List<VillaNumero>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Lista de villas Cardoso Resort</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="VillaNumero" asp-action="Create" class="btn btn-secondary">
                    <i class="bi bi-plus-circle"></i> Criar nova villa number
                </a>
            </div>
        </div>

        <table class="table" align="center">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Villa.Nome)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Villa_Numero)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Detalhes_Especiais)
                    </th>
                    <th>
                        Opções
                    </th>
                </tr>
            <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                                @Html.DisplayFor(modelItem => item.VillaId)
                        </td>
                        <td>
                                @Html.DisplayFor(modelItem => item.Villa_Numero)
                        </td>
                        <td>
                                @Html.DisplayFor(modelItem => item.Detalhes_Especiais)
                        </td>


                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="VillaNumero" asp-action="Atualizar" asp-route-villaNumeroId="@item.Villa_Numero" class="btn btn-success mx-2">
                                    <i class="bi bi-pencil">Modificar</i>
                                </a>
                                <a asp-controller="VillaNumero" asp-action="Apagar" asp-route-villaNumeroId="@item.Villa_Numero" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash">Apagar</i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    }
            </tbody>
        </table>
    </div>