WhiteLaggon.Web/Controllers/VillaFracaoController.cs
using CardosoResort.Domain.Entities;
using CardosoResort.Infrastructure.Data;
using CardosoResort.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CardosoResort.Web.Controllers
{
    public class VillaFracaoController : Controller
    {
        //Com .net Core o contexto do banco de dados é injetado no controlador por meio do construtor
        //Portanto apenas buscamos o DB que já foi configurado no Program.cs e buscamos a implementação do DbContext
        //O que vai configurar a connectionString, abrir connexao e dar a connexao
        private readonly ApplicationDbContext _db;

        public VillaFracaoController(ApplicationDbContext db)
        {
            //Aqui, Dependency Injection é usada para injetar o contexto do banco de dados no controlador
            _db = db;
        }

        public IActionResult Index()
        {
            //Usamos o método Include para incluir a entidade relacionada Villa na consulta. Assim, podemos acessar as propriedades da entidade relacionada na visualização.
            //Até podemos usar outro Include para incluir mais entidades relacionadas
            var villasFracoes = _db.VillaFracoes.Include(u => u.Villa).ToList();
            return View(villasFracoes);
        }

        public IActionResult Create()
        {
            //DropdownList Com viewBag para a view
            //ViewBag.VILLAS = new SelectList(_db.Villas, "Id", "Nome");

            //Fazer o dropdownList com ViewModel sem usar ViewBag. É mais seguro e mais limpo segundo o livro
            VillaFracaoVM villaFracaoVM = new VillaFracaoVM //Instanciamos um novo objeto da classe VillaFracaoVM
            {
                VillaFracao = new VillaFracao(),
                VillaLista = new SelectList(_db.Villas, "Id", "Nome")
            };

            return View(villaFracaoVM);
        }

        [HttpPost]
        public IActionResult Create(VillaFracaoVM objeto)
        {
            //ModelState.Remove("Villa"); //caso nao metemos [validadeNever] no propriedade  VillaFracao

            //Verificar se existe Villa_Fracao na base de dados com o mesmo numero da villaFracao
            bool villaFracaoExiste = _db.VillaFracoes.Any(vf => vf.Villa_Fracao == objeto.VillaFracao.VillaId);
            if (villaFracaoExiste)
            {
                TempData["error"] = "Numero da Fração já existe"; //Usamos TempData para enviar uma mensagem de erro para a próxima solicitação
                ModelState.AddModelError("Villa_Fracao", "Numero da villa já existe"); //Adicionamos um erro ao modelo

                //Precisamos recarregar a lista de villas para o dropdownList após a validação, caso contrário, a lista será perdida
                //DropdownList para o ViewModel
                objeto.VillaLista = new SelectList(_db.Villas, "Id", "Nome");
                return View(objeto); //Se o modelo não for válido mandar de volta para a página de criação
            }

            if (ModelState.IsValid && !villaFracaoExiste)
            {
                _db.VillaFracoes.Add(objeto.VillaFracao);
                _db.SaveChanges();
                TempData["success"] = "Numero para a vila foi criada com sucesso"; //Usamos TempData para enviar uma mensagem de sucesso para a próxima solicitação
                return RedirectToAction("Index"); //Se o modelo for válido, redirecionamos para a página de índice
            }
            return View(); //Se o modelo não for válido mandar de volta para a página de criação
        }

        public IActionResult Atualizar(int villaFracaoId)
        {
            VillaFracao? villaFracaoObj = _db.VillaFracoes.FirstOrDefault(v => v.Villa_Fracao == villaFracaoId); //Buscamos a fraccao pelo id
            if (villaFracaoObj == null) //Se a fracao não for encontrada, retornamos um erro 404
            {
                return RedirectToAction("Error", "Home");
            }

            return View(villaFracaoObj);
        }

        [HttpPost]
        public IActionResult Atualizar(Villa villa)
        {
            if (villa.Nome == villa.Descricao)
            {
                ModelState.AddModelError("Descricao", "O nome e a descrição não podem ser iguais");
            }
            if (ModelState.IsValid)
            {
                _db.Villas.Update(villa);
                _db.SaveChanges();
                //      TempData["success"] = "Villa foi atualizada com sucesso"; //Usamos TempData para enviar uma mensagem de sucesso para a próxima solicitação
                return RedirectToAction("Index"); //Se o modelo for válido, redirecionamos para a página de índice
            }
            // TempData["error"] = "Erro ao atualizar a villa"; //Usamos TempData para enviar uma mensagem de erro para a próxima solicitação
            return View(); //Se o modelo não for válido mandar de volta para a página de criação
        }

        public IActionResult Apagar(int villaId)
        {
            Villa? villa = _db.Villas.FirstOrDefault(v => v.Id == villaId); //Buscamos a villa pelo id
            if (villa is null) //Usar o operador de nulidade para verificar se a villa é nula, evita overflow
            {
                return RedirectToAction("Error", "Home");
            }
            else
            {
                return View(villa);
            }
        }

        [HttpPost]
        public IActionResult Apagar(Villa villa)
        {
            //
            Villa? villaDb = _db.Villas.FirstOrDefault(v => v.Id == villa.Id); //Buscamos a villa pelo id
            if (villaDb is not null)
            {
                _db.Villas.Remove(villaDb);
                _db.SaveChanges();
                //        TempData["success"] = "Villa foi removida com sucesso"; //Usamos TempData para enviar uma mensagem de sucesso para a próxima solicitação
                //palavra success tem que ser igual a que está no arquivo _Layout.cshtml
                return RedirectToAction("Index");
            }
            //    TempData["error"] = "Villa não encontrada"; //Usamos TempData para enviar uma mensagem de erro para a próxima solicitação
            return View();
        }
    }
}

WhiteLaggon.Web/Views/VillaFracao/Apagar.cshtml
@model VillaFracaoVM      /*Sem @model VillaFracao*/

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Apagar Fração @Model.VillaFracao.Villa_Fracao</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">

            <div class="p-3">
                <input asp-for="@Model.VillaFracao.Villa_Fracao" hidden /> @*para nao ser visivel. é necessario para o post
                <div asp-validation-summary="All"></div> @*linha para colocar todos as validacoes*@
                <div class="form-floating py-1 col-12">
                    <select asp-for="@Model.VillaFracao.VillaId" disabled asp-items="@Model.VillaLista" class="form-select border shadow">
                        <option disabled selected>- Selecione a Villa -</option>
                    </select>
                    <label asp-for="@Model.VillaFracao.VillaId" class="ms-2"></label>
                    <span asp-validation-for="@Model.VillaFracao.VillaId" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.VillaFracao.Villa_Fracao" disabled class="form-control border shadow" />
                    <label asp-for="@Model.VillaFracao.Villa_Fracao" class="ms-2"></label>
                    <span asp-validation-for="@Model.VillaFracao.Villa_Fracao" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.VillaFracao.Detalhes_Especiais" disabled class="form-control border shadow" />
                    <label asp-for="@Model.VillaFracao.Detalhes_Especiais" class="ms-2"></label>
                    <span asp-validation-for="@Model.VillaFracao.Detalhes_Especiais" class="text-danger"></span>
                </div>

            </div>

            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-danger w-100">
                        <i class="bi bi-trash-fill"></i> Apagar
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="VillaFracao" asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"></i> Cancelar
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>


@*Valida;oes no lado do cliente. Assim, nao ]e preciso fazer post*@
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteLaggon.Web/Views/VillaFracao/Atualizar.cshtml
@model VillaFracaoVM      /*Sem @model VillaFracao*/

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Atualizar Fração @Model.VillaFracao.Villa_Fracao</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            
            <div class="p-3">
                <input asp-for="@Model.VillaFracao.Villa_Fracao" hidden /> @*para nao ser visivel. é necessario para o post
                <div asp-validation-summary="All"></div> @*linha para colocar todos as validacoes*@
                <div class="form-floating py-1 col-12">
                    <select asp-for="@Model.VillaFracao.VillaId" asp-items="@Model.VillaLista" class="form-select border shadow">
                        <option disabled selected>- Selecione a Villa -</option>
                    </select>   
                    <label asp-for="@Model.VillaFracao.VillaId" class="ms-2"></label>
                    <span asp-validation-for="@Model.VillaFracao.VillaId" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.VillaFracao.Villa_Fracao" disabled class="form-control border shadow" />
                    <label asp-for="@Model.VillaFracao.Villa_Fracao" class="ms-2"></label>
                    <span asp-validation-for="@Model.VillaFracao.Villa_Fracao" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="@Model.VillaFracao.Detalhes_Especiais" class="form-control border shadow" />
                    <label asp-for="@Model.VillaFracao.Detalhes_Especiais" class="ms-2"></label>
                    <span asp-validation-for="@Model.VillaFracao.Detalhes_Especiais" class="text-danger"></span>
                </div>

            </div>

            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-success w-100">
                        <i class="bi bi-check-circle"></i> Atualizar
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="VillaFracao" asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"></i> Cancelar
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>


@*Valida;oes no lado do cliente. Assim, nao ]e preciso fazer post*@
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteLaggon.Web/Views/VillaFracao/Create.cshtml
@model VillaFracao

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Criar novo Villa numero</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <div class="p-3">
                @*<div asp-validation-summary="All"></div> @*linha para colocar todos as validacoes*@
                <div class="form-floating py-1 col-12">
                    <select asp-for="@Model.VillaId" asp-items="@ViewBag.VILLAS" class="form-select border shadow">
                        <option disabled selected>- Selecione a Villa -</option>
                    </select>
                    <label asp-for="VillaId" class="ms-2"></label>
                    <span asp-validation-for="VillaId" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Villa_Fracao" class="form-control border shadow" />
                    <label asp-for="Villa_Fracao" class="ms-2"></label>
                    <span asp-validation-for="Villa_Fracao" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Detalhes_Especiais" class="form-control border shadow" />
                    <label asp-for="Detalhes_Especiais" class="ms-2"></label>
                    <span asp-validation-for="Detalhes_Especiais" class="text-danger"></span>
                </div>
            </div>

            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-success w-100">
                        <i class="bi bi-check-circle"></i> Criar
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="VillaFracao" asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"></i> Cancelar
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>


@*Valida;oes no lado do cliente. Assim, nao ]e preciso fazer post*@
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteLaggon.Web/Views/VillaFracao/Index.cshtml
@model List<VillaFracao>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Lista de Frações Cardoso Resort</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="VillaFracao" asp-action="Create" class="btn btn-secondary">
                    <i class="bi bi-plus-circle"></i> Criar nova Fração
                </a>
            </div>
        </div>

        <table class="table table-hover" align="center">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Villa.Nome)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Villa_Fracao)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Detalhes_Especiais)
                    </th>
                    <th>
                        Opções
                    </th>
                </tr>
            <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                                @Html.DisplayFor(modelItem => item.Villa.Nome)
                        </td>
                        <td>
                                @Html.DisplayFor(modelItem => item.Villa_Fracao)
                        </td>
                        <td>
                                @Html.DisplayFor(modelItem => item.Detalhes_Especiais)
                        </td>


                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="VillaFracao" asp-action="Atualizar" asp-route-villaFracaoId="@item.Villa_Fracao" class="btn btn-success mx-2">
                                    <i class="bi bi-pencil"> Modificar</i>
                                </a>
                                <a asp-controller="VillaFracao" asp-action="Apagar" asp-route-villaFracaoId="@item.Villa_Fracao" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash"> Apagar</i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    }
            </tbody>
        </table>
    </div>