WhiteLaggon.Web/Controllers/VillaController.cs
using CardosoResort.Application.Common.Interfaces;
using CardosoResort.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CardosoResort.Web.Controllers
{
    [Authorize] //Atributo que indica que apenas utilizadores autenticados podem aceder a este controlador
    public class VillaController : Controller
    {
        //##################################################################################################################################Agora usando IVillaRepository
        //private readonly IVillaRepository _villaRepo; //Aqui estamos injetando a dependência do IVillaRepository no controlador

        //Usando UnitOfWork
        private readonly IUnitOfWork _unitOfWork; //Aqui estamos injetando a dependência do IUnitOfWork no controlador

        private readonly IWebHostEnvironment _webHostingEnvironment; //Aqui estamos injetando a dependência do IWebHostEnvironment no controlador

        public VillaController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostingEnvironment)
        {
            //Aqui, Dependency Injection é usada para injetar o contexto do banco de dados no controlador
            _unitOfWork = unitOfWork;
            _webHostingEnvironment = webHostingEnvironment;
        }

        public IActionResult Index()
        {
            var villas = _unitOfWork.Villas.GetAll(); //Aqui estamos chamando o método GetAll do repositório de Villa para obter todas as villas
            return View(villas);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Villa villa)
        {
            if (villa.Nome == villa.Descricao)
            {
                ModelState.AddModelError("Descricao", "O nome e a descrição não podem ser iguais");
            }
            if (ModelState.IsValid)
            {
                if (villa.Imagem != null) //Se a imagem não for nula
                {
                    string nomeFicheiro = Guid.NewGuid().ToString() + Path.GetExtension(villa.Imagem.FileName); //Criamos um nome de ficheiro único para a imagem da villa
                    string caminho = Path.Combine(_webHostingEnvironment.WebRootPath, @"images\VillaImagens"); //Definimos o caminho onde a imagem será guardada no servidor web
                    using var ficheiroStream = new FileStream(Path.Combine(caminho, nomeFicheiro), FileMode.Create); //Criamos um ficheiro no servidor web  para guardar a imagem da villa com using para garantir que o ficheiro é fechado após o uso
                    villa.Imagem.CopyTo(ficheiroStream); //Copiamos a imagem para o ficheiro

                    villa.ImagemUrl = "/images/VillaImagens/" + nomeFicheiro; //Definimos a propriedade ImagemUrl da villa com o caminho da imagem
                }
                else
                {
                    villa.ImagemUrl = "https://placehold.co/600x400";
                }

                _unitOfWork.Villas.Add(villa); //Adicionamos a villa ao repositório
                _unitOfWork.Villas.Save(); //Salvamos as alterações no banco de dados

                TempData["success"] = "Villa foi criada com sucesso"; //Usamos TempData para enviar uma mensagem de sucesso para a próxima solicitação
                return RedirectToAction(nameof(Index)); //Se o modelo for válido, redirecionamos para a página de índice
            }
            TempData["error"] = "Erro ao criar a villa"; //Usamos TempData para enviar uma mensagem de erro para a próxima solicitação
            return View(); //Se o modelo não for válido mandar de volta para a página de criação
        }

        public IActionResult Atualizar(int villaId)
        {
            Villa? objeto = _unitOfWork.Villas.Get(v => v.Id == villaId); //Buscamos a villa pelo id usando o método Get do repositório
            if (objeto == null) //Se a villa não for encontrada, retornamos um erro 404
            {
                return RedirectToAction("Error", "Home");
            }

            return View(objeto);
        }

        [HttpPost]
        public IActionResult Atualizar(Villa villa)
        {
            if (villa.Nome == villa.Descricao)
            {
                ModelState.AddModelError("Descricao", "O nome e a descrição não podem ser iguais");
            }

            if (ModelState.IsValid && villa.Id > 0)
            {
                if (villa.Imagem != null) //Se a imagem não for nula
                {
                    string nomeFicheiro = Guid.NewGuid().ToString() + Path.GetExtension(villa.Imagem.FileName); //Criamos um nome de ficheiro único para a imagem da villa
                    string caminho = Path.Combine(_webHostingEnvironment.WebRootPath, @"images\VillaImagens"); //Definimos o caminho onde a imagem será guardada no servidor web

                    //Sempre que atualizamos, devemos excluir a imagem antiga
                    if (!string.IsNullOrEmpty(villa.ImagemUrl)) //Se a propriedade ImagemUrl da villa não for nula ou vazia
                    {
                        var caminhoImagemAntiga = Path.Combine(_webHostingEnvironment.WebRootPath, villa.ImagemUrl.TrimStart('/')); //Definimos o caminho da imagem antiga

                        if (System.IO.File.Exists(caminhoImagemAntiga))
                        //Se o ficheiro existir, excluímos o ficheiro antigo
                        {
                            System.IO.File.Delete(caminhoImagemAntiga);
                        }
                    }

                    using var ficheiroStream = new FileStream(Path.Combine(caminho, nomeFicheiro), FileMode.Create); //Criamos um ficheiro no servidor web  para guardar a imagem da villa com using para garantir que o ficheiro é fechado após o uso
                    villa.Imagem.CopyTo(ficheiroStream); //Copiamos a imagem para o ficheiro

                    villa.ImagemUrl = "/images/VillaImagens/" + nomeFicheiro; //Definimos a propriedade ImagemUrl da villa com o caminho da imagem
                }
                //Nao queremos substituir a imagem antiga se o utilizador não carregar uma nova imagem
                //else
                //{
                //    villa.ImagemUrl = "https://placehold.co/600x400";
                //}

                _unitOfWork.Villas.Update(villa); //Atualizamos a villa no repositório
                _unitOfWork.Villas.Save(); //Salvamos as alterações no banco de dados
                TempData["success"] = "Villa foi atualizada com sucesso"; //Usamos TempData para enviar uma mensagem de sucesso para a próxima solicitação
                return RedirectToAction(nameof(Index)); //Se o modelo for válido, redirecionamos para a página de índice
            }

            TempData["error"] = "Erro ao atualizar a villa"; //Usamos TempData para enviar uma mensagem de erro para a próxima solicitação
            return View(); //Se o modelo não for válido mandar de volta para a página de criação
        }

        public IActionResult Apagar(int villaId)
        {
            Villa? villa = _unitOfWork.Villas.Get(v => v.Id == villaId); //Buscamos a villa pelo id
            if (villa is null) //Usar o operador de nulidade para verificar se a villa é nula, evita overflow
            {
                return RedirectToAction("Error", "Home");
            }
            else
            {
                return View(villa);
            }
        }

        [HttpPost]
        public IActionResult Apagar(Villa villa)
        {
            //
            Villa? villaDb = _unitOfWork.Villas.Get(v => v.Id == villa.Id); //Buscamos a villa pelo id
            if (villaDb is not null)
            {
                //Sempre que atualizamos, devemos excluir a imagem antiga
                if (!string.IsNullOrEmpty(villa.ImagemUrl)) //Se a propriedade ImagemUrl da villa não for nula ou vazia
                {
                    var caminhoImagem = Path.Combine(_webHostingEnvironment.WebRootPath, villa.ImagemUrl.TrimStart('/')); //Definimos o caminho da imagem

                    if (System.IO.File.Exists(caminhoImagem))
                    //Se o ficheiro existir, excluímos o ficheiro antigo
                    {
                        System.IO.File.Delete(caminhoImagem);
                    }
                }

                _unitOfWork.Villas.Remove(villaDb); //Removemos a villa do repositório
                _unitOfWork.Villas.Save(); //Salvamos as alterações no banco de dados
                TempData["success"] = "Villa foi removida com sucesso"; //Usamos TempData para enviar uma mensagem de sucesso para a próxima solicitação
                //palavra success tem que ser igual a que está no arquivo _Layout.cshtml
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "Villa não encontrada"; //Usamos TempData para enviar uma mensagem de erro para a próxima solicitação
            return View();
        }
    }
}

WhiteLaggon.Web/Views/Villa/Apagar.cshtml
@model Villa

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Apagar @Model.Nome</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <div class="col-10">
                <div class="p-3">
                    <input asp-for="Id" hidden /> @*para nao ser visivel. é necessario para o post
                    para saber qual o id do objeto que esta a ser editado. Recomendaçao colocar no inicio do formulario
                    *@
                    <div asp-validation-summary="All"></div> @*linha para colocar todos as validacoes*@
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Nome" class="form-control border shadow" disabled />

                        <label asp-for="Nome" class="ms-2"></label>
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Descricao" class="form-control border shadow" disabled />
                        <label asp-for="Descricao" class="ms-2"></label>
                        <span asp-validation-for="Descricao" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Preco" class="form-control border shadow" disabled />
                        <label asp-for="Preco" class="ms-2"></label>
                        <span asp-validation-for="Preco" class="text-danger"></span>
                    </div>

                    <div class="form-floating py-1 col-12">
                        <input asp-for="Metros_Quadrados" class="form-control border shadow" disabled />
                        <label asp-for="Metros_Quadrados" class="ms-2"></label>
                        <span asp-validation-for="Metros_Quadrados" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Ocupacao" class="form-control border shadow" disabled />
                        <label asp-for="Ocupacao" class="ms-2"></label>
                        <span asp-validation-for="Ocupacao" class="text-danger"></span>
                    </div>

                    <div class="form-floating py-1 col-12">
                        <input asp-for="Imagem" class="form-control border shadow" />
                        <input asp-for="ImagemUrl" hidden class="form-control border shadow" />
                        <label asp-for="ImagemUrl" class="ms-2"></label>
                        <span asp-validation-for="ImagemUrl" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="col-2">
                <img src="@Model.ImagemUrl" class="img-fluid align-content-center" width="100%" style="border-radius:5px; border:1px solid #bbb9b9" /> @*imagem do objeto que esta a ser editado*@
            </div>
            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-danger w-100">
                        <i class="bi bi-trash-fill"></i> Apagar
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"></i> Cancelar
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>


@*Valida;oes no lado do cliente. Assim, nao ]e preciso fazer post*@
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteLaggon.Web/Views/Villa/Atualizar.cshtml
@model Villa

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Editar @Model.Nome</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden /> @*para nao ser visivel. é necessario para o post
            para saber qual o id do objeto que esta a ser editado. Recomendaçao colocar no inicio do formulario
            *@
            <div class="col-10">
                <div class="p-3">
                    <div asp-validation-summary="All"></div> @*linha para colocar todos as validacoes*@
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Nome" class="form-control border shadow" />
                        <label asp-for="Nome" class="ms-2"></label>
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Descricao" class="form-control border shadow" />
                        <label asp-for="Descricao" class="ms-2"></label>
                        <span asp-validation-for="Descricao" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Preco" class="form-control border shadow" />
                        <label asp-for="Preco" class="ms-2"></label>
                        <span asp-validation-for="Preco" class="text-danger"></span>
                    </div>

                    <div class="form-floating py-1 col-12">
                        <input asp-for="Metros_Quadrados" class="form-control border shadow" />
                        <label asp-for="Metros_Quadrados" class="ms-2"></label>
                        <span asp-validation-for="Metros_Quadrados" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Ocupacao" class="form-control border shadow" />
                        <label asp-for="Ocupacao" class="ms-2"></label>
                        <span asp-validation-for="Ocupacao" class="text-danger"></span>
                    </div>

                    <div class="form-floating py-1 col-12">
                        <input asp-for="Imagem" class="form-control border shadow" />
                        <input asp-for="ImagemUrl" hidden class="form-control border shadow" />
                        <label asp-for="ImagemUrl" class="ms-2"></label>
                        <span asp-validation-for="ImagemUrl" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col-2">
                <img src="@Model.ImagemUrl" class="img-fluid align-content-center" width="100%" style="border-radius:5px; border:1px solid #bbb9b9"/> @*imagem do objeto que esta a ser editado*@ </div>
            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-success w-100">
                        <i class="bi bi-check-circle"></i> Atualizar
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"></i> Cancelar
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>


@*Valida;oes no lado do cliente. Assim, nao ]e preciso fazer post*@
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteLaggon.Web/Views/Villa/Create.cshtml
@model CardosoResort.Domain.Entities.Villa

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Criar nova Villa</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <div class="p-3">
                <div asp-validation-summary="All"></div> @*linha para colocar todos as validacoes*@
                <div class="form-floating py-1 col-12">
                    <input asp-for="Nome" class="form-control border shadow" />
                    <label asp-for="Nome" class="ms-2"></label>
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Descricao" class="form-control border shadow" />
                    <label asp-for="Descricao" class="ms-2"></label>
                    <span asp-validation-for="Descricao" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Preco" class="form-control border shadow" />
                    <label asp-for="Preco" class="ms-2"></label>
                    <span asp-validation-for="Preco" class="text-danger"></span>
                </div>
                
                <div class="form-floating py-1 col-12">
                    <input asp-for="Metros_Quadrados" class="form-control border shadow" />
                    <label asp-for="Metros_Quadrados" class="ms-2"></label>
                    <span asp-validation-for="Metros_Quadrados" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Ocupacao" class="form-control border shadow" />
                    <label asp-for="Ocupacao" class="ms-2"></label>
                    <span asp-validation-for="Ocupacao" class="text-danger"></span>
                </div>

                <div class="form-floating py-1 col-12">
                    <input asp-for="ImagemUrl" hidden class="form-control border shadow" />
                    <input asp-for="Imagem"  class="form-control border shadow" />
                    <label asp-for="ImagemUrl" class="ms-2"></label>
                    <span asp-validation-for="ImagemUrl" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> Criar
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> Cancelar
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


@*Valida;oes no lado do cliente. Assim, nao ]e preciso fazer post*@
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteLaggon.Web/Views/Villa/Index.cshtml
@model List<Villa>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Lista de alojamentos Cardoso Resort</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="Villa" asp-action="Create" class="btn btn-secondary">
                    <i class="bi bi-plus-circle"></i> Criar novo alojamento
                </a>
            </div>
        </div>

        <table class="table table-hover ">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Nome)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Descricao)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Preco)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model[0].Metros_Quadrados)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Ocupacao)
                    </th>
                    <th>
                        Opções
                    </th>



                </tr>
            <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                                @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                                @Html.DisplayFor(modelItem => item.Descricao)
                        </td>
                        <td>
                                @Html.DisplayFor(modelItem => item.Preco)
                        </td>
                        <td>
                                @Html.DisplayFor(modelItem => item.Metros_Quadrados)
                        </td>
                        <td>
                                @Html.DisplayFor(modelItem => item.Ocupacao)
                        </td>

                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Villa" asp-action="Atualizar" asp-route-villaId="@item.Id" class="btn btn-success mx-2">
                                    <i class="bi bi-pencil">Modificar</i>
                                </a>
                                <a asp-controller="Villa" asp-action="Apagar" asp-route-villaId="@item.Id" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash">Apagar</i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    }
            </tbody>
        </table>
    </div>